// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26ACWzsuitSsNBAMeqA64WZ4hfBkfgt4',
    appId: '1:342524601822:web:b5fdcb0ee927d0a72aa94f',
    messagingSenderId: '342524601822',
    projectId: 'appmap-b1a9a',
    authDomain: 'appmap-b1a9a.firebaseapp.com',
    storageBucket: 'appmap-b1a9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnFK79tgRKSO2u5iKU4vhQ-Tt3W4KCH1M',
    appId: '1:342524601822:android:df6e39bdfc56863f2aa94f',
    messagingSenderId: '342524601822',
    projectId: 'appmap-b1a9a',
    storageBucket: 'appmap-b1a9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDyfm947GTWE-NAsyFiOes9I2w45Ju1o',
    appId: '1:342524601822:ios:8d0d13bda20c6cd62aa94f',
    messagingSenderId: '342524601822',
    projectId: 'appmap-b1a9a',
    storageBucket: 'appmap-b1a9a.firebasestorage.app',
    iosBundleId: 'com.example.mapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANDyfm947GTWE-NAsyFiOes9I2w45Ju1o',
    appId: '1:342524601822:ios:8d0d13bda20c6cd62aa94f',
    messagingSenderId: '342524601822',
    projectId: 'appmap-b1a9a',
    storageBucket: 'appmap-b1a9a.firebasestorage.app',
    iosBundleId: 'com.example.mapApp',
  );

}